language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.7.0

# command to install dependencies
install:
  - pip install -r requires.txt --use-mirrors
  - pip install Django==$DJANGO_VERSION --use-mirrors

# command to run tests
script:  python manage.py test test_app
